
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header" style="float: left">
        <a class="navbar-brand" href="0_Forside.ipynb" target="_self"> <h2> &uarr; Tilbake til forsiden</h2></a>
    </div>
  </div>
</nav>

# Intro til Numpy
### Fra matematiske funksjonsuttrykk til python-kode

__Læringsmål__:
* Bli kjent med numpy-typen ndarray
* Kune bruke arrays til å utføre elementvise beregninger

**Oversikt:**
* [Oppgave a) deklarasjon av arrays](#oppg_4a)
* [Oppgave b) elementvis utregning](#oppg_4b)
* [Oppgave c) arrays og funksjoner](#oppg_4c)
* [Oppgave d) mer elementvis utregning](#oppg_4d)
  
NB! Denne oppgaven bes du ikke om å lage funksjoner, men heller variabler med et spesifikkt navn.

### Importering av `numpy`-biblioteket

Numpy er noe som kalles et bibliotek. Dette er kode skrevet for å løse et problem som du kan ta i bruk i din egen kode. Numpy er laget for å gjøre numerikk i python mye lettere. Når man ønsker å bruke et bibliotek må man først fortelle til python at man skal bruke det, det gjør man med å *importere* biblioteket.

In [1]:
import numpy
import numpy as np
from numpy import cos, sin

Ovenfor ser du 3 forskjellige måter å importere funksjonalitet fra biblioteket på. Om du har et prosjekt som bare trenger en veldig liten del av et bibliotek kan det være en fordel å bruke den nederste. Da blir bare relevante funksjoner lastet inn, og du kan skrive navnet direkte istedenfor å måtte skrive `np.cos` eller `np.sin`.

Ellers bruker vi nesten alltid den i midten. Den er ekvivalent med den øverste, men gjør at man slipper å skrive så mye når man bruker biblioteket. Den sier til python at vi ønsker å bruke biblioteket numpy, og vi kaller det for *np*.

### Bruk av biblioteker

Om du ønsker å bruke den nederste linjen til å importere er det veldig lett å bruke funksjonalitetene. Da kaller du funksjonene du har importert som du ville gjort til vanlig. Dette kan gjøre python-program som regner ut matteformler mye lettere å lese.

In [2]:
from numpy import cos, sin

value = 0.7
sinValue = sin(value)
cosValue = cos(value)

print(f"Sin of {value} is {sinValue}")
print(f"Cos of {value} is {cosValue}")

Sin of 0.7 is 0.644217687237691
Cos of 0.7 is 0.7648421872844885


Når vi bruker bibliotek med hjelp av *import numpy as np* gjøres dette relativt likt. Eneste forskjellen er at vi må si til python at vi ønsker å bruke numpy biblioteket med *np.* slik som vist nedenfor.

In [3]:
import numpy as np

value = 0.7
sinValue = np.sin(value)
cosValue = np.cos(value)

print(f"Sin of {value} is {sinValue}")
print(f"Cos of {value} is {cosValue}")

Sin of 0.7 is 0.644217687237691
Cos of 0.7 is 0.7648421872844885


### Numpy-array

Numpy har også noen datatyper som vi kan bruke, og en av de mest vanlige er ndarray (kort for N-dimensjonal array). Dette er litt som en liste, men med funksjonalitet laget for numerikk. Det er også viktig å merke seg at indeksering, slicing, ol er likt som med vanlige lister.

Nedenfor ser du hvordan du lager en slik array.

In [4]:
import numpy as np

my_array = np.array([1, 2, 3])
print(my_array)

[1 2 3]


In [5]:
print(my_array[1])

2


<a id="oppg_4a"></a>
## a)
Bruk funksjonen `numpy.array` til å lage en array `n` med tallverdiene $0,\ 1,\ 2,\ 3,\ 4\ \text{og}\ 5$ i den rekkefølgen
$$n \in \{0, 1, 2, 3, 4, 5\}$$

In [6]:
### BEGIN SOLUTION
n = np.array([0, 1, 2, 3, 4, 5])
### END SOLUTION

In [7]:
print(f"n: {n}")
### BEGIN HIDDEN TESTS
from autofeedback import VariableTests
import numpy as np

test_results = VariableTests()
if isinstance(n, np.ndarray):
    test_results.add_result(True, "variable 'n' is of type numpy array", wgt = 0.5)
    test_results.compare_values(n, np.arange(6))
else:
    test_results.add_result(False, f"variable 'n' is of type {type(n).__name__} and not numpy array")
round(test_results.get_results()*2, 2)
### END HIDDEN TESTS

n: [0 1 2 3 4 5]


2.0

### Regneoperasjoner med numpy array

Det som er spesielt for nympy-arrays er hvordan matematiske operasjoner funker på arrays. Med arrays vil nemlig operasjoner være *elementvis*, noe som vil si at operasjoner vil virke på hvert element hver for seg, istedenfor på hele arrayen. Nedenfor bruker vi my_array fra forrige kodecelle $n \in \{1, 2, 3\}$

In [8]:
my_array * 2

array([2, 4, 6])

In [9]:
my_array - 7

array([-6, -5, -4])

Med denne egenskapen kan man også gjøre vanskeligere operasjoner mulig. Ta for eksempel funksjonen nedenfor
$$x_{k} = \frac{1}{2}\cdot k^2 + 2\cdot k -3, \ \ \ \ \ k \in \{0, 1, 2, 3, 4, 5, 6 ,7 ,8, 9\}$$

Denne kan bli gjort relativt enkelt med numpy.

In [10]:
k = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
xa_k = k**2/2 + 2*k - 3
print(xa_k)

[-3.  -0.5  3.   7.5 13.  19.5 27.  35.5 45.  55.5]


Vi ser her at addisjon `+`, subtraksjon `-` og potensoperasjonen `**` utfører de aktuelle matematiske utregningene på _hvert element_ i array-variabelen `n`.

Dette lar oss utføre rimelig kompliserte og store utregninger med relativt få linjer. Tabellen nedenfor gir en forklaring på hvilke matematiske operatorer som støttes med numpy sine `ndarray` typer:

|Operator | Forklaring|
|---|---|
|+ | Elementvis Addisjon|
|- | Elementvis Subtraksjon|
|* | Elementvis Multiplikasjon|
|** | Elementvis Potensregning|

Når vi bruker numpy sine funksjoner vil også disse kunne brukes på arrays. 

In [11]:
from numpy import sin, cos, sqrt, pi

arr = np.array([pi, 4, 9])
print(sin(arr))
print(cos(arr))
print(sqrt(arr))

[ 1.22464680e-16 -7.56802495e-01  4.12118485e-01]
[-1.         -0.65364362 -0.91113026]
[1.77245385 2.         3.        ]


<a id="oppg_4b"></a>
## b)

Med verdiene i arrayen `n` fra forrige oppgave, lag en ny array `x` med verdier gitt i uttrykket nedenfor.

$$x_n = 0.64^{\frac{n}{2}}, \ \ \ \ \ n \in \{0, 1, 2, 3, 4, 5\}$$

In [12]:
### BEGIN SOLUTION
x = 0.64 ** (n / 2)
### END SOLUTION

In [13]:
print(f"x_n: {x}")
### BEGIN HIDDEN TESTS
from autofeedback import VariableTests
import numpy as np

n_test = np.arange(6)
x_test = 0.64**(n_test/2)

test_results = VariableTests()
if isinstance(x, np.ndarray):
    test_results.compare_values(x, x_test)
else:
    test_results.add_result(False, f"variable 'x' is of type {type(x).__name__} and not numpy array")
round(test_results.get_results()*3, 2)
### END HIDDEN TESTS

x_n: [1.      0.8     0.64    0.512   0.4096  0.32768]


3.0

<a id="oppg_4c"></a>
## c)
Med verdiene i arrayen `n` fra forrige oppgave, lag en ny array `y` som følger sinussekvensen.
$$y_n = \cos \left( \frac{\pi \cdot n}{11} + \frac{\pi}{6} \right), \ \ \ \ \ n \in \{0, 1, 2, 3, 4, 5\}$$

Hint: nympy biblioteket har en konstant kalt pi

In [14]:
### BEGIN SOLUTION
n = np.arange(6)
y = np.cos(np.pi*n/11 + np.pi/6)
### END SOLUTION

In [15]:
print(f"y_n: {y}")
### BEGIN HIDDEN TESTS
from autofeedback import VariableTests
import numpy as np

n_test = np.arange(6)
y_test = np.cos(np.pi*n_test/11+np.pi/6)

test_results = VariableTests()
if isinstance(y, np.ndarray):
    test_results.compare_values(y, y_test)
else:
    test_results.add_result(False, f"variable 'y' is of type {type(y).__name__} and not numpy array")
round(test_results.get_results()*3, 2)
### END HIDDEN TESTS

y_n: [ 0.8660254   0.69007901  0.45822652  0.18925124 -0.09505604 -0.37166246]


3.0

**Flere sekvenser i ett uttrykk.**

Hittil har vi sett på tilfeller hvor vi en av operanden i en regneoperasjon er et enkelt tall, og den andre er en array. Men det er også fullt mulig at begge operander er en array, så lenge de er ***like lange***. 

Se for eksempel på kodesnutten nedenfor:
```python
x1 = np.array([1, 2, 3, 4, 5, 6])
x2 = np.array([6, 5, 4, 3, 2, 1])

x3 = x1/x2
```

Her vil hvert element i `x3` være resulatet av tilsvarende element i `x1` delt på tilsvarende element i `x2`. Med andre ord vil linjen `x3 = x1/x2` gjøre det samme som koden nedenfor:

```python
x3 = np.array([x1[0]/x2[0], 
               x1[1]/x2[1], 
               x1[2]/x2[2], 
               x1[3]/x2[3], 
               x1[4]/x2[4], 
               x1[5]/x2[5]])
```

<a id="oppg_4d"></a>
## d) 
Bruk elementvis multiplikasjon til å lage en array `z` som er _produktet_ av `x`og `y` fra deloppgave __b__ og __c__).
$$z_n = x_n \cdot y_n, \ \ \ \ \ n \in \{0, 1, 2, 3, 4, 5\}$$

In [16]:
### BEGIN SOLUTION
z = x*y
### END SOLUTION

In [17]:
print(f"z_n: {z}")
### BEGIN HIDDEN TESTS
from autofeedback import VariableTests
import numpy as np

n_test = np.arange(6)
x_test = 0.64**(n_test/2)
y_test = np.cos(np.pi*n_test/11+np.pi/6)
z_test = x_test*y_test

test_results = VariableTests()
if isinstance(z, np.ndarray):
    test_results.compare_values(z, z_test)
else:
    test_results.add_result(False, f"variable 'z' is of type {type(z).__name__} and not numpy array")
round(test_results.get_results()*2, 2)
### END HIDDEN TESTS

z_n: [ 0.8660254   0.55206321  0.29326497  0.09689664 -0.03893496 -0.12178635]


2.0

<br>
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <div class="navbar-header" style="float: left">
            <a class="navbar-brand" href="3_Mer_lister_strenger.ipynb" target="_self">&lt; Forrige side: <i>mer om lister og strenger</i></a>
            </div>
        <div class="navbar-header" style="float: right">
            <a class="navbar-brand" href="5_Ofte_brukte_arrays.ipynb" target="_self">Neste side: <i>ofte brukte arrays</i> &gt;</a>
        </div>
    </div>
</nav>